spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
          routes:
            # Example route for user service
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**
              filters:
                - RewritePath=/api/users/(?<segment>.*), /user-service/api/users/${segment}

            # Example route for product service
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/products/**,/api/categories/**
              filters:
                - RewritePath=/api/(?<service>products|categories)/(?<segment>.*), /product-service/api/${service}/${segment}

            # Example route for order service
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/order/**
              filters:
                - RewritePath=/api/order/(?<segment>.*), /order-service/api/order/${segment}

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8087/eureka-discovery/eureka/

# Logging configuration for debugging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes,httptrace
  endpoint:
    health:
      show-details: always