spring:
  application:
    name: eureka-discovery
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
  client:
    fetch-registry: false
    register-with-eureka: false
    region: us-east
    service-url:
      defaultZone: http://localhost:8087/eureka-discovery/eureka/
    availability-zones:
      default: us-east-1

server:
  address: localhost
  port: 8087
  servlet:
    context-path: /eureka-discovery