server:
  port: 8087

spring:
  application:
    name: eureka-server

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
    response-cache-update-interval-ms: 1000
    response-cache-auto-expiration-in-seconds: 180
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8087/eureka-discovery/eureka/
    eureka-server-connect-timeout-seconds: 60
    eureka-server-read-timeout-seconds: 60
  instance:
    hostname: localhost
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  level:
    com.netflix.eureka: ERROR
    com.netflix.discovery: ERROR