spring:
  application:
    name: eureka-discovery
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    availability-zones:
      default: us-east-1a
    sevice-url:
      defaultZone: http://localhost:8087/eureka-discovery/eureka/
server:
  address: localhost
  port: 8087
  servlet:
    context-path: /eureka-discovery