spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ProductService
    username: ecommerceProduct
    password: product1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8087/eureka-discovery/eureka/
    register-with-eureka: true
    fetch-registry: true
