spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/UserService
    driver-class-name: org.postgresql.Driver
    username: ecommerceUser
    password: user1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true